### ISSUE TITLE
Suggestion: copy as Json

### ISSUE THREAD

**Issue by PhiLhoSoft** [redmunds/brackets-display-shortcuts#43]
The Copy to Current Document button isn't very useful, IMHO.
It might be more interesting to be able to copy as Json, in the format used in the keymap.json format. That would allow to easily override some shortcuts / commands.
Or perhaps add it as a context menu on a selected line in the table: I select a command / shortcut, I want it inserted in the current file, which would be likely to be this keymap.json...

**Comment by redmunds** [comment]
@PhiLhoSoft Copy to Current Document is meant for generating markup (e.g. to paste into a wiki page), so I don't want to remove that.

I agree that this should work better with the override shortcut functionality recently added to Brackets. I was thinking about providing a right-click menu on shortcuts and provide with an "Override" Command. Override Command would open keymap.json file and insert an entry for selected shortcut. User would have to manually edit existing shortcut to new shortcut and then Save file. How does that sound?

At the very least, panel should allow selection so you can copy a command id (which I tried to do recently :) ).

Care to submit a pull request?

**Comment by PhiLhoSoft** [comment]
Yes, I refrained from suggesting to remove the current button... :-) It can be useful... in some rare cases! :-D

For the pull request, I am currently learning how extensions work in Brackets, so it might take a while. ;-)

**Comment by redmunds** [comment]
@PhiLhoSoft I added Override Shortcut and Disable Shortcut commands in [this pull request](https://github.com/redmunds/brackets-display-shortcuts/pull/45). Does this satisfy you need?

**Comment by PhiLhoSoft** [comment]
Nice. I suggest to detect if a command is already disabled, so the menu acts as a toggle: I was able to deactivate twice the same command, resulting in a duplicated line in the keymap.json file.
The issue might be tracking the current assignment, to be able to restore it...

The Override shortcut command is a bit ambiguous, as it results instead in an override of the command, where we define a new shortcut for it. Or perhaps there should be both capabilities?

Side note: you add tabs in this file that seems to use spaces for indenting.

**Comment by redmunds** [comment]
@PhiLhoSoft Thanks for reviewing these changes! Comments below.

> I suggest to detect if a command is already disabled, so the menu acts as a toggle: I was able to deactivate twice the same command, resulting in a duplicated line in the keymap.json file.
The issue might be tracking the current assignment, to be able to restore it...

This functionality simplify facilitates editing the **keymap.json** file. It makes copying the command ids and keybindings easier. It would be a fair amount of work to get even a little smarter, so I probably won't be trying to do that.

The `KeyBindingManager` validates the file when you hit Save, but I guess that case is not critical enough to detect -- it shouldn't cause any problems in your configuration.

One update that I will consider (i.e. need to research) is to update the update the Shortcuts panel when **keymap.json** file is Saved to disk and keybindings are updated. This will fix the problem with being able to disable a shortcut twice because it will no longer be in the list. 

> The Override shortcut command is a bit ambiguous, as it results instead in an override of the command, where we define a new shortcut for it. Or perhaps there should be both capabilities?

You can't really override a command from here, but I think the command name could be more clear. What do you think about "Override Shortcut for Command" ?

> Side note: you add tabs in this file that seems to use spaces for indenting.

The code should use your indent settings when editing that file. That's what you'll get when editing that file manually (using *Debug > Open User Key Map*), so that seems like the right thing to do. Let me know if it's not using your settings.

**Comment by redmunds** [comment]
>> The Override shortcut command is a bit ambiguous, as it results instead in an override of the command, where we define a new shortcut for it. Or perhaps there should be both capabilities?

> You can't really override a command from here, but I think the command name could be more clear. What do you think about "Override Shortcut for Command" ?

Actually, it's valid to have multiple shortcuts for a single command, so maybe message should say "Add Shortcut for Command" ?

**Comment by PhiLhoSoft** [comment]
> This functionality simplify facilitates editing the keymap.json file.

OK, fair enough. And of course the toggle can be made just by removing the override.

"Add Shortcut for Command" sounds good.

[Off Topic] I didn't realize all these caps in menu items. I wonder what UI guideline they follow. Windows guideline recommend using simpler "Add shortcut for command", less sententious... Capitalized first letters are reserved for titles (of windows, of sections, etc.).

**Comment by redmunds** [comment]
Good question about the capitalization. I looked at the context menus in Brackets and the words that are *key* to the command seem to be capitalized, so this seems consistent and  I'll just leave it like this for now. Thanks for your feedback!

Merged with https://github.com/redmunds/brackets-display-shortcuts/pull/46. Closing this issue.
