### ISSUE TITLE
[reccomendation] enter shortcut in search bar

### ISSUE THREAD

**Issue by koopaTroopa1** [redmunds/brackets-display-shortcuts#54]
after pressing `ctrl-alt-/` it would be nice to be able to select the 'filter' search bar, and press the shortcut you want to search. and have it typed in. for example, i want to filter for the keyboard shortcut `ctrl-a`. so i press `ctrl-alt-/` and click the filter box. then i press `ctrl-a` and it is automatically typed in

**Comment by redmunds** [comment]
@koopaTroopa1 Thanks for your suggestion. I don't think that it could work quite that way because the Filter field is the only field that can have focus, so it has focus by default, and the first click on any line would automatically filter by that Shortcut, and I don't think that's desired.

Did you know that you can click on any column header to sort by that column? Click again to reverse the order. That provides some quick pseudo-filtering, but, of course, just for the starting characters.

A new context (right-click) menu item could be added, but I'm not sure exactly what you want to filter on. Currently filter on works on text in Command Name. If a "Filter by Command Name" item was added, it would usually only return that single item since Commands Names should be unique. Please provide more details.

**Comment by koopaTroopa1** [comment]
Ok. I didnt know that you could 'click on any column header to sort by that column'. That works just as well. thanks
